### PR TITLE
2230 mobile tooltips

### PR DESCRIPTION
**Pull request by calvinfroedge**
Completion of issue outlined in https://github.com/bitshares/bitshares-ui/issues/2230

Usage example included in `app/components/Basic/index.js`

### CODE REVIEW

**Comment by calvinfroedge** [comment]
@startailcoon @sschiessl-bcp @gibbsfromncis Hoping to get a review on this. Thanks!

**Comment by sschiessl-bcp** [comment]
@gibbsfromncis could you review please?

**Comment by gibbsfromncis** [comment]
@calvinfroedge I have the following comments:

1. Please do not use mentions of Bitshares in style-guide's components. (rename BitsharesTooltip to Tooltip or CustomTooltip)
2. We use tooltips for Desktop & Mobile devices (both). Me (personally) use Tooltip on Desktop very often. You took our solution and re-implemented it for Mobile devices only. Now we have all tooltips for desktop broken.  

If you want to have Mobile-Only solution please create separate component like "TooltipMobile". If you want to **extend** antd functionality - please extend it instead of removing features we already had. 

The idea of style-guide is to help developers in bitshares-ui team to dev project faster and more easier. 

If you see that you need some additional functionality please add support of custom prop like "mobile Tooltip={Boolean}". All components in style-guide must perform all ant design features.

**Comment by calvinfroedge** [comment]
@gibbsfromncis Changes were made. I used my previous version that allowed to optionally have EITHER regular Ant tooltip or pass `withQuestionIcon` prop to force the question icon tooltip. 

I also removed mention of "Bitshares" in the styleguide component.

I don't think `mobileTooltip={true}` is a good prop to pass, because as @startailcoon mentioned many of the desktop tooltips use the question mark...it's better to just say the style of tooltip you want and let the breakpoint manage whether or not it's mobile width or not.

**Comment by calvinfroedge** [comment]
@gibbsfromncis Bump

**Comment by gibbsfromncis** [comment]
@calvinfroedge it looks fine to me 👍

**Comment by sschiessl-bcp** [comment]
I need to evaluate if I can do what we need in the UI with that, see 
https://github.com/bitshares/bitshares-ui/issues/2230

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp thanks for your feedback.

@calvinfroedge please add some examples of forms, tabs with your tooltip and provide a licecap or screenshots

**Comment by sschiessl-bcp** [comment]
I can see it in the examples from bitshares style guide, just need to get around to to example implementation in UI to get a grip on it

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I want these examples to be presented in https://styleguide.bitshares.org/#/dark so anyone can see it and take a look. Also I'm interested how these tooltips will look like on ant forms and ant tabs. If it looks well I'm pretty sure they will looks normally on any place. 

@calvinfroedge please when you add examples to style-guide post a screenshots for each theme. I want to make sure:
1) tooltips looks well on each theme
2) tooltips default color variable is placed .less configs.

**Comment by gibbsfromncis** [comment]
@calvinfroedge any updates?

**Pull request closed without merging**
